/// Flutter icons LipSurf
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LipSurf
///      fonts:
///       - asset: fonts/LipSurf.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class LipSurf {
  LipSurf._();

  static const _kFontFam = 'LipSurf';

  static const IconData ok = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mail_outline = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData forum = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData check_circle = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData warning_empty = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData lightbulb = const IconData(0xf0eb, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xf4ac, fontFamily: _kFontFam);
}
